<?php

namespace MM\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use MM\PLatformBundle\Entity\Comment;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByPage($page, $nbPerPage)
  	{	
    $query = $this->createQueryBuilder('a')
      ->orderBy('a.date', 'DESC')
      ->getQuery()
    ;

    $query
      // On définit l'annonce à partir de laquelle commencer la liste
      ->setFirstResult(($page-1) * $nbPerPage)
      // Ainsi que le nombre d'annonce à afficher sur une page
      ->setMaxResults($nbPerPage)
    ;

    // Enfin, on retourne l'objet Paginator correspondant à la requête construite
    // (n'oubliez pas le use correspondant en début de fichier)
    return new Paginator($query, true);
  	}

  	public function findByAll()
  	{	
    return $this->createQueryBuilder('a')
      ->orderBy('a.date', 'DESC')
      ->getQuery()
      ->getResult()
    ;
  	}
  	
  	public function findByComment(Comment $comment)
  	{
  	  return $this->createQueryBuilder('a')
  	  ->where('a.id = :id')
  	  ->setParameter('id', $comment->getThread()->getArticleId())
  	  ->getQuery()
  	  ->getResult()
  	;
  	}
}
