<?php

namespace MM\PlatformBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
  	public function findByAll()
  	{	
    return $this->createQueryBuilder('a')
      ->orderBy('a.date', 'DESC')
      ->getQuery()
      ->getResult()
    ;
  	}
}
