<?php

namespace MM\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByAll() {	
    return $this->createQueryBuilder('a')
      ->getQuery()
      ->getResult()
    ;
  	}
}
